// <auto-generated />
namespace bookStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedmoreattrs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmoreattrs));
        
        string IMigrationMetadata.Id
        {
            get { return "201806151311511_added more attrs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
